### ISSUE TITLE
New version cannot be used？

### ISSUE THREAD

**Issue by tomoat** [Miramac/vscode-exec-node#10]
vscode: 2.1.6
node-exec version:0.2.3
os: macos sierra 10.12.3

The new version of the new bug,and old version does not have this bug
Can you help me？

![image](https://cloud.githubusercontent.com/assets/7428698/23212637/99100b22-f942-11e6-9c71-cfbc78f27bee.png)

**Comment by Miramac** [comment]
I'm really sorry for this bug! Unfortunately I can not reproduce it... But I guess it has something to do with the newly introduced options.
I published a new version. Please also try to uninstall and reinstall the extention.

**Comment by tomoat** [comment]
I tried to uninstall and reinstall the new version of 0.2.4, but the problem still exists, I installed the 0.2.2 version is no problem

**Comment by Miramac** [comment]
Which version of node.js do you use?

**Comment by tomoat** [comment]
node version: v7.5.0
